#spring.application.name=dental-clinic-scheduler
#
#server.port=8080
#
#spring.thymeleaf.cache=false

spring.application.name=dental-clinic-scheduler
server.port=${PORT:8080}
spring.thymeleaf.cache=false